services:
  postgres:
    image: postgres:16
    container_name: shareit-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    volumes:
      - shareit-postgres-data:/var/lib/postgresql/data

volumes:
  shareit-postgres-data: